version: '3'

services:
  xz-car-catalog:
    container_name: car-catalog-web
    image: xz/car-catalog:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 3500:3000
    volumes:
      - .:/var/app
    command: npm run start

  
  
  